### ISSUE TITLE
Mudar o datatype DATE para DATETIME nos schemas das tabelas que contêm este tipo.

### ISSUE THREAD

**Issue by jlucsx** [PJI110-SALA-001GRUPO-009-2023/read-together-server#11]
## Motivação

Atualmente, não importa o formato de data/hora que enviamos, o banco sempre salva no formato "yyyy-mm-dd". 
![image](https://user-images.githubusercontent.com/42000540/230526123-97c55d78-b087-49c6-a1ca-cc08f8f28325.png)

Contudo, para registros de tempo precisos e, principalmente, para consulta da data e horário da reunião do mês, precisaremos que o componente de tempo também seja persistido.

## Objetivo

Utilizar o tipo de dado DATETIME ao invés de DATE, em nossas tabelas.

**Comment by julioroncal** [comment]
Obrigado pela observação.!
OB levantada.
