### ISSUE TITLE
Adição de novas colunas e atualização de outras já existentes na Tabela CLUBE

### ISSUE THREAD

**Issue by jlucsx** [PJI110-SALA-001GRUPO-009-2023/read-together-server#16]
## Motivação

Para refletir as mudanças no design da aplicação, é necessário adicionar/alterar os campos/colunas para:
| Coluna        	| Tipo de dado  	| Tipo de modificação
|---------------	|--------------------  |---	
| nome          	| VARCHAR(100)  	| Alteração  	
| subtitulo     	| VARCHAR(100)  	| Adição  	
| categoria     	| VARCHAR(100)  	| Adição  	
| site          	| VARCHAR(2048) 	| Adição
| whatsapp      	| VARCHAR(2048) 	| Adição  	
| telegram      	| VARCHAR(2048) 	| Adição  	
| redes_sociais | TEXT          	        | Adição  	

### Observações
- Os campos site, whatsapp e telegram serão URLs e embora o padrão de URL de whatsapp e telegram sejam bem menores em caracteres, dadas às várias informações adicionais que a API de links do whatsapp permite (creio que telegram tenha uma também), acrescentei o valor máximo de URL por precaução - o tipo varchar adequa ao que for inputado, de toda forma;
- Coluna nome foi extendida para suportar 100 caracteres em vez dos 45 anteriores. A motivação é a expectativa de nomes maiores para o clube do livro.

Antecipei as alterações em meu banco de dados locais com o script abaixo. Sintam-se à vontade para adequá-lo da maneira como preferirem.
```sql
ALTER TABLE `mydb`.`CLUBE` 
ADD COLUMN `subtitulo` VARCHAR(100) NULL DEFAULT NULL AFTER `nome`,
ADD COLUMN `categoria` VARCHAR(100) NULL DEFAULT NULL AFTER `dt_criacao`,
ADD COLUMN `site` VARCHAR(2048) NULL DEFAULT NULL AFTER `categoria`,
ADD COLUMN `whatsapp` VARCHAR(2048) NULL DEFAULT NULL AFTER `site`,
ADD COLUMN `telegram` VARCHAR(2048) NULL DEFAULT NULL AFTER `whatsapp`,
ADD COLUMN `redes_sociais` TEXT NULL DEFAULT NULL AFTER `telegram`,
CHANGE COLUMN `nome` `nome` VARCHAR(100) NOT NULL ;
```

**Comment by jlucsx** [comment]
Uma outra informação: o tipo de dado TEXT para a coluna redes_sociais foi colocado pela imprevisibilidade na quantidade de redes sociais que podem ser inseridas no campo "Redes Sociais" no formulário.
Este tipo de dado pode armazenar até 65.535 caracteres. Sintam-se à vontade para mudá-lo para VARCHAR(n), sendo n o valor escolhido, caso pareça mais sensato.

**Comment by marlonbl** [comment]
Foram adicionados os novos campos no modelo da tabela "CLUBE".
(ver anexo)

Sobre a definição entre TEXT ou VARCHAR -- acho que vai depender muito do que desejamos para esse campo.

TEXT costuma ser mais lento e não permite indexação direta, mas funciona bem para armazenar dado estático que será consultado poucas vezes. VARCHAR tende a ser mais rápido, em especial quando há múltiplas consultas, mas é melhor quando o tamanho é menor.  

Para REDES_SOCIAIS -- Como esperamos que seja utilizado? É um campo acessório de informação complementar, voltado para cadastrar uma string livre com os endereços das redes sociais do usuário?

Estou fechando essa issue, mas podemos reabri-la, caso necessário.

![Tabela-CLUBE-Atualizada_20230418](https://user-images.githubusercontent.com/123337591/232798950-12034013-6a4e-4229-91f3-cad691773cb1.jpg)
