### ISSUE TITLE
Alterar tamanho do campo de senha no DB

### ISSUE THREAD

**Issue by felipe-dmb** [PJI110-SALA-001GRUPO-009-2023/read-together-server#17]
## Motivação

Atualmente o campo de senha possui 45 caracteres, porém o hash com `bcrypt` necessita de 60 caracteres.
Alteração já realizada no prisma em:

- #15 

## Objetivo

Suportar o hash gerado pelo `bcrypt` de 60 caracteres

**Comment by marlonbl** [comment]
Campo "senha" da tabela "USUARIO" alterado para tamanho 60 caracteres.
(ver anexo)

![Tabela_USUARIO_atualizacao_Campo_SENHA-20230418](https://user-images.githubusercontent.com/123337591/232802984-458320a9-2efb-49de-932b-75760b55de50.jpg)
