### ISSUE TITLE
Suporte a Validação

### ISSUE THREAD

**Issue by felipe-dmb** [PJI110-SALA-001GRUPO-009-2023/read-together-server#5]
## Motivação

Não devemos confiar nos dados que recebemos de qualquer fonte externa. Para isso, usamos a validação para aumentar a segurança da aplicação.

## Pacotes e Documentação

Alguns pacotes famosos:

- [Joi](https://joi.dev/api/?v=17.9.1)
- [Yup](https://github.com/jquense/yup)

**Comment by julioroncal** [comment]
"Joi-browser": É uma versão para o navegador do "joi", que é uma biblioteca de validação de dados popular para Node.js. Ela permite que você faça validações de dados no navegador, sem a necessidade de um servidor Node.js.
