### ISSUE TITLE
Persistência de Convites e Lista de Interessados

### ISSUE THREAD

**Issue by felipe-dmb** [PJI110-SALA-001GRUPO-009-2023/read-together-server#8]
## Motivação

Atualmente, não está claro como será armazenado o status de usuários que estejam na lista de interessados (aguardando aprovação do moderador), ou convites (aguardando aceite de leitores).

## Objetivo

Propor solução para o status de usuários que estejam na lista de interessados ou de convidados.

**Comment by julioroncal** [comment]
Interessante pergunta. pelo que entendi, o cadastro é autónomo com a decisão de registro de cada usuario da plataforma. O status para ser admitido num Clube, depende de cada moderador, por isso criei a entidade "Lista de Espera",  responsavel por receber os usuarios e cataloga com o binario (Aceito / Na espera) até ser aceitos como participante na leitura.

**Comment by felipe-dmb** [comment]
Será uma tabela para ambos os casos (Convite e Interssados)?

- Convite: Moderador envia convite para alguém se tornar leitor
- Interessado: não-membro se inscreve na lista de espera para aprovação do moderador

Além disso, precisamos prever mais um caso:
- Em espera
- Negado
- Aceito

Para o caso de aceito, podemos remover da tabela de Lista de Espera, e acrescentar nos membros. Usando transações, só afeta o banco se ambas as querys rodar com sucesso.
